version: '3.7'

services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: wakeupbot:latest
        restart: 'no'
        stop_signal: SIGINT
        environment:
            BOT_TOKEN:
            BOT_SU:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB:
            POSTGRES_HOST: "db"
            POSTGRES_PORT: "5432"
            REDIS_HOST: "redis"
            REDIS_PORT: "6379"
            REDIS_DB:

            PROXY_URL:
            PROXY_USERNAME:
            PROXY_PASSWORD:

            DOMAIN:
            BOT_PUBLIC_PORT:
            WEBHOOK_BASE_PATH:

            SUPERUSER_STARTUP_NOTIFIER:
            DOTENV_LOADED: "True"
        networks:
            - net
        volumes:
            - ./logs:/app/logs
        depends_on:
            - db
            - redis

    db:
        image: 'postgres:alpine'
        restart: 'no'
        environment:
            POSTGRES_USER:
            POSTGRES_PASSWORD:
            POSTGRES_DB:
        networks:
            - net
        volumes:
            - dbdata:/var/lib/postgresql/data

    redis:
        image: 'redis:alpine'
        command: redis-server --appendonly yes
        restart: 'no'
        networks:
            - net
        volumes:
            - redisdata:/data
networks:
    net:

volumes:
    dbdata:
        name: wakeupbot-db
    redisdata:
        name: wakeupbot-redis
